backend: Add missing `policies` directory
ChiselStrike expects a policies directory to exist; otherwise it wont run:

penberg@vonneumann backend % npm run dev

> backend@1.0.0 dev
> chisel dev

🚀 Thank you for your interest in the ChiselStrike beta! 🚀

⚠️  This software is for evaluation purposes only. Do not use it in production. ⚠️

📚 Docs:    https://docs.chiselstrike.com
💬 Discord: https://discord.gg/4B5D7hYwub
📧 Email:   beta@chiselstrike.com

For any question, concerns, or early feedback, please contact us via email or Discord!

[2022-06-16T14:40:47Z] INFO - ChiselStrike is ready 🚀 - URL: http://localhost:8080
Model defined: UrlSlug
End point defined: /dev/url
Error: No path was found. about ["policies"]